# Generated by Django 3.1 on 2020-12-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0031_auto_20201221_2009'),
        ('Customer', '0006_auto_20201219_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.product'),
        ),
    ]
