# Generated by Django 3.1 on 2020-12-22 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 20, 13, 35, 140668), null=True),
        ),
    ]
