# Generated by Django 3.1 on 2020-12-24 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_bid_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 21, 1, 49, 418084), null=True),
        ),
    ]
