# Generated by Django 3.1 on 2020-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0006_auto_20201123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.DateTimeField(null=True),
        ),
    ]
