# Generated by Django 3.1 on 2020-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_auto_20201127_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
