# Generated by Django 3.1 on 2020-11-28 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_auto_20201128_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='use_type',
            field=models.CharField(choices=[('Unlimited', 'Unlimited'), ('Use', 'Use')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 17, 20, 29, 958831), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 17, 20, 29, 958831), null=True),
        ),
    ]
