# Generated by Django 3.1 on 2020-11-28 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_auto_20201128_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('use_type', models.CharField(choices=[('Unlimited', 'Unlimited')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Coupons',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 17, 24, 8, 203566), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 17, 24, 8, 203566), null=True),
        ),
    ]
