# Generated by Django 3.1 on 2021-01-09 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0037_auto_20201224_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_bid',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 19, 58, 59, 648276), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 19, 58, 59, 648276), null=True),
        ),
    ]
